### ISSUE TITLE
Sphinx theme

### ISSUE THREAD

**Issue by alfiopuglisi** [ArcetriAdaptiveOptics/arte#10]
The default theme is quite horrible. Can we change to a more readable html theme? the "nature" theme is very similar to the numpy/scipy website

**Comment by lbusoni** [comment]
sure, I think it is the one by default in readthedocs, but I do agree that
the one of scipy is better. I don't know how it will appear on
arte.readthedocs.org though

Il giorno sab 18 apr 2020 alle ore 10:02 Alfio Puglisi <
notifications@github.com> ha scritto:

**Comment by lbusoni** [comment]
Very nice Nature theme committed in 0df1b4df2147931a306cfa55e91fae516673d26e, much nicer than the old one!! It is rendered correctly on readthedocs as well
