### ISSUE TITLE
Numpy version

### ISSUE THREAD

**Issue by alfiopuglisi** [ArcetriAdaptiveOptics/arte#16]
in discrete_fourier_transform: fft direct and inverse do not work with astropy units and numpy < 1.18, because units are not conserved. We need a way of checking the numpy version, or write code that works in both cases (sometimes not easy).

In various points in the library I've put unit checks that maybe were only needed on my computer, which was running numpy == 1.16 up to five minutes ago.

**Comment by lbusoni** [comment]
commit cd797822a0899f07ce97941305b776de8f5da8b6 forces numpy > 1.17 that
fixes these checks. On my computer with numpy=1.18 fft units are properly
managed, with 1.16 they are not.


Il giorno mar 28 apr 2020 alle ore 21:37 Alfio Puglisi <
notifications@github.com> ha scritto:

**Comment by lbusoni** [comment]
I will close this, as it looks like numpy version is now properly managed
