### ISSUE TITLE
What is the role of utils.help?

### ISSUE THREAD

**Issue by lbusoni** [ArcetriAdaptiveOptics/arte#17]
In which conditions utils.help is more helpful than the standard help()? 
(I didn't look into the details of utils.help, so it may have some additional feature that makes it a better choice than the standard help)
Or, slightly different question: do we want the arte library to have all (or most of) its modules passed through the decorator add_help? Or the idea is to provide utils.help as is, to be used in some externally developed application?

**Comment by alfiopuglisi** [comment]
It's a module that I wrote once to be a near-clone of the elab_lib help.
wrt. the standard help() the output is a lot more compact, can search for
substrings, and is recursive like the elab one. Personally I prefer it over
the output of help() that prints the whole docstring, but it's a matter of
taste. The recursive search in elab_lib was very useful.

The idea was to decorate most classes, but if the decorator form is too
invasive, we can think of something else. Apart from the method decorators
for customization, it just walks over the class members to extract
information from their signature and docstrings.

**Comment by alfiopuglisi** [comment]
The new help form is easier to use since it is enough to decorate the base class, and it will go recursively into all methods and members.
