### ISSUE TITLE
ModalDecomposer does not work if the slope vector is smaller than the zernike mask

### ISSUE THREAD

**Issue by alfiopuglisi** [ArcetriAdaptiveOptics/arte#48]
The ModalDecomposer.measureZernikeCoefficientsFromSlopes() is able to handle a small zernike mask with a larger slope vector, by manipulating the mask, but not the other way around. This happens for example when a round zernike mask is used to project a slope map from a real system that has an obstruction inside, and thus some slopes are missing: the zernike mask has a larger number of elements and the projection fails.

This test fails because in the third line we mask out some slopes inside the pupil, while it works without the slope removal:

    def testMaskWithSmallerSlopeMap(self):
        md = ModalDecomposer(3)
        slopeMask = CircularMask((200, 200), 90, [100, 100])
        slopeMask.mask()[100,100] = True   # Mask out slopes inside the pupil
        mapX = np.ma.masked_array(np.arange(40000).reshape((200, 200)), mask=slopeMask.mask())
        mapY = mapX.T
        slopes = Slopes(mapX, mapY)
        mask = CircularMask((200, 200), 90, [100, 100])
        md.measureZernikeCoefficientsFromSlopes(slopes, mask)

**Comment by lbusoni** [comment]
addressed in branch #49

**Comment by alfiopuglisi** [comment]
Fixed by https://github.com/ArcetriAdaptiveOptics/arte/pull/49, closing
