### ISSUE TITLE
remove non-public data

### ISSUE THREAD

**Issue by lbusoni** [ArcetriAdaptiveOptics/arte#8]
Like things coming from consortia documents. We should check what is publicly released (e.g. on ESO web page) and what is not.

**Comment by alfiopuglisi** [comment]
In arte/astro/n_phot.py there is the Maory magnitude model, how to check
whether it is public or not?

**Comment by lbusoni** [comment]
for that specific example I guess they are public as the background is coming from http://www.eso.org/gen-fac/pubs/astclim/paranal/skybackground/
Anyhow, I don't think is useful to have a maory_model in arte: it is better to have a dedicated maory project extending arte. 
The same applies to atmo.cn2_profiles.EsoEltProfiles and MaoryStereoScidarProfiles: I'll move them elsewhere.
We should keep here in arte only the generic class and the widely accepted case.

**Comment by lbusoni** [comment]
This one is fixed now
