### ISSUE TITLE
which docstring style?

### ISSUE THREAD

**Issue by lbusoni** [ArcetriAdaptiveOptics/arte#9]
Should we decide on a docstring stlye? numpydoc? google? sphinx? 
Do we have already a good complete example to copy from?
If yes let's add it to code_convention.py

**Comment by alfiopuglisi** [comment]
I had already added the convention of using numpydoc... as a proposal :)
Complete examples can be found at
https://numpydoc.readthedocs.io/en/latest/example.html#source

**Comment by lbusoni** [comment]
Ok, this is set. 
I also added interpshinx to docs/conf.py to allow crosslinking to the docs of external packages which is useful when we have parameters or returns value that are defined in numpy/scipy/astropy/...
